In [1]:
%matplotlib inline
import pandas as pd

In [2]:
from IPython.core.display import HTML
css = open('style-table.css').read() + open('style-notebook.css').read()
HTML('<style>{}</style>'.format(css))

In [3]:
titles = pd.DataFrame.from_csv('data/titles.csv', index_col=None)
titles.head()

                     title  year
0           The Rising Son  1990
1  The Thousand Plane Raid  1969
2         Crucea de piatra  1993
3                  Country  2000
4               Gaiking II  2011

In [4]:
cast = pd.DataFrame.from_csv('data/cast.csv', index_col=None)
cast.head()

                    title  year     name   type                character     n
0         Suuri illusioni  1985   Homo $  actor                   Guests  22.0
1     Battle of the Sexes  2017  $hutter  actor          Bobby Riggs Fan  10.0
2    Secret in Their Eyes  2015  $hutter  actor          2002 Dodger Fan   NaN
3              Steve Jobs  2015  $hutter  actor  1988 Opera House Patron   NaN
4  Straight Outta Compton  2015  $hutter  actor              Club Patron   NaN

### How many movies are listed in the titles dataframe?

In [6]:
len(cast.title)

3554507

### What are the earliest two films listed in the titles dataframe?

In [7]:
cast.sort('year')

/Users/sheena/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:1: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  if __name__ == '__main__':

,title,year,name,type,character,n
2475884,Miss Jerry,1894,Blanche Bayliss,actress,Miss Geraldine Holbrook (Miss Jerry),NaN
547504,Miss Jerry,1894,Chauncey Depew,actor,Himself - the Director of the New York Central...,NaN
457752,Miss Jerry,1894,William Courtenay,actor,Mr. Hamilton,NaN
1692218,Soldiers of the Cross,1900,Reg Perry,actor,Lion,NaN
1692067,Soldiers of the Cross,1900,Orrie Perry,actor,Lion,NaN
591883,Valsons,1905,Armand Dranem,actor,Himself,NaN
468045,The Story of the Kelly Gang,1906,Sam Crewes,actor,Dan Kelly,NaN
3415469,The Story of the Kelly Gang,1906,Elizabeth Tait,actress,Kate Kelly,1.0
1370251,The Story of the Kelly Gang,1906,Mr. Marshall,actor,Dan Kelly,NaN
711431,The Story of the Kelly Gang,1906,John (III) Forde,actor,Dan Kelly,NaN
3548077,Lika mot lika,1906,Tollie Zellman,actress,"Clara, kammarjungfru",3.0
1563281,The Joe Gans-Battling Nelson Fight,1906,Battling Nelson,actor,Himself,2.0
642444,The Story of the Kelly Gang,1906,Jack (II) Ennis,actor,Steve Hart,NaN
461793,The Story of the Kelly Gang,1906,Will Coyne,actor,Joe Byrne,NaN
318802,The Story of the Kelly Gang,1906,Norman (II) Campbell,actor,Steve Hart,NaN
1423710,The Story of the Kelly Gang,1906,Mr. McKenzie,actor,Steve Hart,NaN
2974824,Lika mot lika,1906,Helfrid Lambert,actress,Suzanne,2.0
1207924,Lika mot lika,1906,Knut Lambert,actor,Coq-H?ron,1.0
2114427,The Story of the Kelly Gang,1906,John Tait,actor,School Master,2.0
2114418,The Story of the Kelly Gang,1906,Frank Tait,actor,Extra,NaN
1471076,The Story of the Kelly Gang,1906,Frank (VI) Mills,actor,Ned Kelly,NaN
755057,The Joe Gans-Battling Nelson Fight,1906,Joe Gans,actor,Himself,1.0
2114417,The Story of the Kelly Gang,1906,E.J. Tait,actor,Extra,NaN
598803,Robbery Under Arms,1907,William Duff,actor,Trooper,4.0
2219926,Robbery Under Arms,1907,Lance Vane,actor,Inspector of Police,3.0
851821,Robbery Under Arms,1907,Arthur Guest,actor,Curate,5.0
777704,Robbery Under Arms,1907,Jim Gerald,actor,Warrigal,1.0
1449346,Robbery Under Arms,1907,George Merriman,actor,Warder,2.0
2516776,The Fairylogue and Radio-Plays,1908,Mrs. Bostwick,actress,Mme. Grogand - the Baker's Wife,31.0
921544,The Fairylogue and Radio-Plays,1908,Daniel (III) Heath,actor,Tertius - an Islander,16.0
...,...,...,...,...,...,...
15096,"Unity, Guardians Versus Corruption: War of Ages",2021,Tyler Adornato,actor,Zignitch,NaN
22657,"Unity, Guardians Versus Corruption: War of Ages",2021,Zack Akerman,actor,Crazing,NaN
22656,"Unity, Guardians Versus Corruption: War of Ages",2021,Zack Akerman,actor,Rocko8u,NaN
2071524,Battle of Evil: The Evil of the Dark,2021,Isaac Stevenson,actor,Bratt Smith,NaN
15093,"Unity, Guardians Versus Corruption: War of Ages",2021,Tyler Adornato,actor,Xile,NaN
15094,"Unity, Guardians Versus Corruption: War of Ages",2021,Tyler Adornato,actor,Mike,NaN
562993,Fast & Furious 10,2021,Vin Diesel,actor,Dominic Toretto,NaN
15095,"Unity, Guardians Versus Corruption: War of Ages",2021,Tyler Adornato,actor,Clockwork,NaN
15097,"Unity, Guardians Versus Corruption: War of Ages",2021,Tyler Adornato,actor,Trok,NaN
22658,"Unity, Guardians Versus Corruption: War of Ages",2021,Zack Akerman,actor,Aqua,NaN
395131,The Hamster,2021,Jack Christophe,actor,Jack T. Cat,NaN
1213764,Avatar 4,2022,Stephen Lang,actor,Miles Quaritch,NaN
2633076,Clutch Control,2022,Barbara Dabson,actress,Katy,NaN
112740,Clutch Control,2022,Josh (XXII) Baker,actor,Alex Simmons,NaN
3026121,Clutch Control,2022,Emelia Marshall Lovsey,actress,Wedding Guest,NaN
991548,Clutch Control,2022,Karl Hughes,actor,Dewie Dayton,NaN
1548627,Clutch Control,2022,Rishi Nair,actor,Toby Glenshaw,NaN
355153,Ready N' Reloaded,2022,Gabe Cazeau,actor,Captain Bryan Jones,NaN
1464284,Ready N' Reloaded,2022,Faton Millanaj,actor,FBI Agent Darren Smith,NaN
1891073,Austin Powers Meets Monty Python Meets the Who...,2022,Mike Sabulsky,actor,A YOUNG AUSTIN POWERS AND AN ELDERLY MONTY PYT...,NaN
409850,Out of the Mountains,2022,Tallis Clayton,actor,John Allen,NaN
2286470,Ready N' Reloaded,2022,Xaiven (III) Watson,actor,FBI Agent Carter Watson,NaN
1970569,Clutch Control,2022,Paul (III) Sharman,actor,Wedding Guest,NaN
3310408,Avatar 4,2022,Zoe Saldana,actress,Neytiri,NaN
2566306,Clutch Control,2022,Ellen (II) Carter,actress,Leslie Whitehorn,NaN
3104818,Clutch Control,2022,Olivia Millar-Ross,actress,Lisa Watts,NaN
2981037,Clutch Control,2022,Annie Larkin,actress,Wedding Guest,NaN
2531128,Clutch Control,2022,Gracie Brooke,actress,Cindy Simmons,NaN
2355772,Avatar 4,2022,Sam Worthington,actor,Jake Sully,NaN
1103193,Xenomorph,2023,Max (IV) Kaufman,actor,Jake,NaN

### How many movies have the title "Hamlet"?

In [9]:
len(cast[cast.title == 'Hamlet'])

313

### How many movies are titled "North by Northwest"?

In [10]:
len(cast[cast.title == 'North by Northwest'])

111

### When was the first movie titled "Hamlet" made?

In [12]:
cast[cast.title == 'Hamlet'].sort('year')

/Users/sheena/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:1: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  if __name__ == '__main__':

,title,year,name,type,character,n
1521931,Hamlet,1910,Jean Mounet-Sully,actor,Hamlet,NaN
1214884,Hamlet,1911,Oscar Langkilde,actor,Horatio,6.0
2386094,Hamlet,1911,Einar Zangenberg,actor,Laertes,5.0
2968458,Hamlet,1911,Ella La Cour,actress,Gertrude,3.0
1567972,Hamlet,1911,Alwin Neu?,actor,Hamlet,1.0
940340,Hamlet,1911,Aage Hertel,actor,Claudius,2.0
3316367,Hamlet,1911,Emilie Sannom,actress,Ophelia,4.0
709408,Hamlet,1913,Johnston Forbes-Robertson,actor,Hamlet,2.0
1811708,Hamlet,1913,Percy Rhodes,actor,The Ghost,6.0
1815847,Hamlet,1913,G. (II) Richards,actor,Bernardo,12.0
1825694,Hamlet,1913,Walter Ringham,actor,Claudius,1.0
1834895,Hamlet,1913,A. Roberts,actor,Marcellus,11.0
3270938,Hamlet,1913,Olive Richardson,actress,Player Queen,NaN
1493043,Hamlet,1913,R. Montague,actor,Priest,19.0
916954,Hamlet,1913,George Hayes,actor,Osric,10.0
1947361,Hamlet,1913,Alex Scott-Gatty,actor,Laertes,5.0
172039,Hamlet,1913,Grendon Bentley,actor,Fortinbras,7.0
130641,Hamlet,1913,J.H. Barnes,actor,Polonius,4.0
1884161,Hamlet,1913,Montagu Rutherford,actor,Rosencrants,8.0
2704857,Hamlet,1913,Gertrude Elliot,actress,Ophelia,21.0
13672,Hamlet,1913,Eric Adeney,actor,Reynaldo,14.0
2518394,Hamlet,1913,Adeleine Bourne,actress,Gertrude,20.0
1676742,Hamlet,1913,S.T. Pearce,actor,Second Gravedigger,18.0
645398,Hamlet,1913,E. Ericson,actor,Francisco,13.0
440620,Hamlet,1913,S.A. Cookson,actor,Horatio,3.0
51474,Hamlet,1913,Richard Andean,actor,Second Player,16.0
1864843,Hamlet,1913,E.A. Ross,actor,Guildenstern,9.0
1887468,Hamlet,1913,J.H. Ryley,actor,First Gravedigger,17.0
527191,Hamlet,1921,Anton De Verdier,actor,Laertes,7.0
2890139,Hamlet,1921,Lilly Jacobson,actress,Ophelia,8.0
...,...,...,...,...,...,...
2338664,Hamlet,2011,Peter Wingfield,actor,Claudius,3.0
1776689,Hamlet,2011,Bruce Ramsay,actor,Hamlet,1.0
1837347,Hamlet,2011,Russell Roberts,actor,King Hamlet,NaN
2100764,Hamlet,2011,Haig Sutherland,actor,Laertes,NaN
2002578,Hamlet,2011,Martin Sims,actor,Guildenstern,NaN
2155601,Hamlet,2011,Michael Tiernan,actor,Policeman,NaN
2464215,Hamlet,2011,Gillian Barber,actress,Gertrude,NaN
347206,Hamlet,2011,John Cassini,actor,Butler,NaN
838418,Hamlet,2015,Dean Gregory,actor,Lucianus,14.0
2547053,Hamlet,2015,Michelle Butterly,actress,1st Gravedigger,11.0
2494330,Hamlet,2015,Gillian Bevan,actress,Polonia,4.0
1988114,Hamlet,2015,John Shrapnel,actor,Claudius,2.0
1988115,Hamlet,2015,John Shrapnel,actor,Ghost,2.0
78583,Hamlet,2015,Thomas (II) Arnold,actor,Horatio,5.0
2005578,Hamlet,2015,Peter Singh,actor,Guildenstern,9.0
1568597,Hamlet,2015,Tachia Newall,actor,Priest,13.0
1568596,Hamlet,2015,Tachia Newall,actor,Reynaldo,13.0
1568595,Hamlet,2015,Tachia Newall,actor,Francisco,13.0
2484781,Hamlet,2015,Claire Benedict,actress,Player King,8.0
3506461,Hamlet,2015,Katie (II) West,actress,Ophelia,7.0
2081490,Hamlet,2015,Ben Stott,actor,Bernardo,12.0
2081491,Hamlet,2015,Ben Stott,actor,Osric,12.0
2081492,Hamlet,2015,Ben Stott,actor,Player Queen,12.0
2484780,Hamlet,2015,Claire Benedict,actress,Marcella,8.0
3062466,Hamlet,2015,Barbara Marten,actress,Gertrude,3.0
3205782,Hamlet,2015,Maxine Peake,actress,Hamlet,1.0
3088367,Hamlet,2015,Jodie McNee,actress,Rosencrantz,10.0
3088368,Hamlet,2015,Jodie McNee,actress,2nd Gravedigger,10.0
2391958,Hamlet,2015,Ashley Zhangazha,actor,Laertes,6.0
2547052,Hamlet,2015,Michelle Butterly,actress,Margaret,11.0

### List all of the "Treasure Island" movies from earliest to most recent.

In [15]:
hi = (cast[cast.title == 'Hamlet']).sort('year')

/Users/sheena/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:1: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  if __name__ == '__main__':

In [16]:
print(hi)

          title  year                       name     type           character  \
1521931  Hamlet  1910          Jean Mounet-Sully    actor              Hamlet
1214884  Hamlet  1911            Oscar Langkilde    actor             Horatio
2386094  Hamlet  1911           Einar Zangenberg    actor             Laertes
2968458  Hamlet  1911               Ella La Cour  actress            Gertrude
1567972  Hamlet  1911                 Alwin Neu?    actor              Hamlet
940340   Hamlet  1911                Aage Hertel    actor            Claudius
3316367  Hamlet  1911              Emilie Sannom  actress             Ophelia
709408   Hamlet  1913  Johnston Forbes-Robertson    actor              Hamlet
1811708  Hamlet  1913               Percy Rhodes    actor           The Ghost
1815847  Hamlet  1913           G. (II) Richards    actor            Bernardo
1825694  Hamlet  1913             Walter Ringham    actor            Claudius
1834895  Hamlet  1913                 A. Roberts    actor           Marcellus
3270938  Hamlet  1913           Olive Richardson  actress        Player Queen
1493043  Hamlet  1913                R. Montague    actor              Priest
916954   Hamlet  1913               George Hayes    actor               Osric
1947361  Hamlet  1913           Alex Scott-Gatty    actor             Laertes
172039   Hamlet  1913            Grendon Bentley    actor          Fortinbras
130641   Hamlet  1913                J.H. Barnes    actor            Polonius
1884161  Hamlet  1913         Montagu Rutherford    actor         Rosencrants
2704857  Hamlet  1913            Gertrude Elliot  actress             Ophelia
13672    Hamlet  1913                Eric Adeney    actor            Reynaldo
2518394  Hamlet  1913            Adeleine Bourne  actress            Gertrude
1676742  Hamlet  1913                S.T. Pearce    actor  Second Gravedigger
645398   Hamlet  1913                 E. Ericson    actor           Francisco
440620   Hamlet  1913               S.A. Cookson    actor             Horatio
51474    Hamlet  1913             Richard Andean    actor       Second Player
1864843  Hamlet  1913                  E.A. Ross    actor        Guildenstern
1887468  Hamlet  1913                 J.H. Ryley    actor   First Gravedigger
527191   Hamlet  1921           Anton De Verdier    actor             Laertes
2890139  Hamlet  1921             Lilly Jacobson  actress             Ophelia
...         ...   ...                        ...      ...                 ...
2338664  Hamlet  2011            Peter Wingfield    actor            Claudius
1776689  Hamlet  2011               Bruce Ramsay    actor              Hamlet
1837347  Hamlet  2011            Russell Roberts    actor         King Hamlet
2100764  Hamlet  2011            Haig Sutherland    actor             Laertes
2002578  Hamlet  2011                Martin Sims    actor        Guildenstern
2155601  Hamlet  2011            Michael Tiernan    actor           Policeman
2464215  Hamlet  2011             Gillian Barber  actress            Gertrude
347206   Hamlet  2011               John Cassini    actor              Butler
838418   Hamlet  2015               Dean Gregory    actor            Lucianus
2547053  Hamlet  2015          Michelle Butterly  actress     1st Gravedigger
2494330  Hamlet  2015              Gillian Bevan  actress             Polonia
1988114  Hamlet  2015              John Shrapnel    actor            Claudius
1988115  Hamlet  2015              John Shrapnel    actor               Ghost
78583    Hamlet  2015         Thomas (II) Arnold    actor             Horatio
2005578  Hamlet  2015                Peter Singh    actor        Guildenstern
1568597  Hamlet  2015              Tachia Newall    actor              Priest
1568596  Hamlet  2015              Tachia Newall    actor            Reynaldo
1568595  Hamlet  2015              Tachia Newall    actor           Francisco
2484781  Hamlet  2015            Claire Benedict  actress         Player King
3506461  Hamlet  2015            Katie (II) West  actress             Ophelia
2081490  Hamlet  2015                  Ben Stott    actor            Bernardo
2081491  Hamlet  2015                  Ben Stott    actor               Osric
2081492  Hamlet  2015                  Ben Stott    actor        Player Queen
2484780  Hamlet  2015            Claire Benedict  actress            Marcella
3062466  Hamlet  2015             Barbara Marten  actress            Gertrude
3205782  Hamlet  2015               Maxine Peake  actress              Hamlet
3088367  Hamlet  2015                Jodie McNee  actress         Rosencrantz
3088368  Hamlet  2015                Jodie McNee  actress     2nd Gravedigger
2391958  Hamlet  2015           Ashley Zhangazha    actor             Laertes
2547052  Hamlet  2015          Michelle Butterly  actress            Margaret

            n
1521931   NaN
1214884   6.0
2386094   5.0
2968458   3.0
1567972   1.0
940340    2.0
3316367   4.0
709408    2.0
1811708   6.0
1815847  12.0
1825694   1.0
1834895  11.0
3270938   NaN
1493043  19.0
916954   10.0
1947361   5.0
172039    7.0
130641    4.0
1884161   8.0
2704857  21.0
13672    14.0
2518394  20.0
1676742  18.0
645398   13.0
440620    3.0
51474    16.0
1864843   9.0
1887468  17.0
527191    7.0
2890139   8.0
...       ...
2338664   3.0
1776689   1.0
1837347   NaN
2100764   NaN
2002578   NaN
2155601   NaN
2464215   NaN
347206    NaN
838418   14.0
2547053  11.0
2494330   4.0
1988114   2.0
1988115   2.0
78583     5.0
2005578   9.0
1568597  13.0
1568596  13.0
1568595  13.0
2484781   8.0
3506461   7.0
2081490  12.0
2081491  12.0
2081492  12.0
2484780   8.0
3062466   3.0
3205782   1.0
3088367  10.0
3088368  10.0
2391958   6.0
2547052  11.0

[313 rows x 6 columns]

### How many movies were made in the year 1950?

In [17]:
len(cast[cast.year == 1950])

21928

### How many movies were made in the year 1960?

In [18]:
len(cast[cast.year == 1960])

18211

### How many movies were made from 1950 through 1959?

In [19]:
len(cast[(cast.year >= 1950) & (cast.year <=1959)])

209808

### In what years has a movie titled "Batman" been released?

In [27]:
see = cast[cast.title == 'Batman'] 
see

,title,year,name,type,character,n
93944,Batman,1943,Frank Austin,actor,Hotel Clerk,NaN
94448,Batman,1943,William Austin,actor,Alfred Pennyworth,NaN
111972,Batman,1989,Del Baker,actor,Napier Hood,31.0
117367,Batman,1989,Michael Balfour,actor,Scientist,44.0
147200,Batman,1989,David Baxt,actor,Dr. Thomas Wayne,48.0
195866,Batman,1989,Paul Birchard,actor,Another Reporter,55.0
207947,Batman,1989,Hugo Blick,actor,Young Jack Napier,41.0
254492,Batman,1943,Lynton Brent,actor,Intended Lockwood Pilot,NaN
282792,Batman,1943,Roy Bucko,actor,Barfly,NaN
373804,Batman,1989,Carl Chase,actor,Goon,14.0
381823,Batman,1943,George Chesebro,actor,Brennan [Ch. 1-3,NaN
442646,Batman,1989,George Lane Cooper,actor,Goon,16.0
461731,Batman,1989,Harold Coyne,actor,Gotham City Pedestrian,NaN
462883,Batman,1989,Edwin Craig,actor,Rotelli,20.0
470182,Batman,1943,Douglas Croft,actor,Robin,2.0
470183,Batman,1943,Douglas Croft,actor,Dick Grayson,2.0
482523,Batman,1989,Clive Curtis,actor,Goon in Bell-Tower,NaN
482579,Batman,1943,Dick Curtis,actor,Agent Croft of Section 50 [Ch. 10-12]),NaN
484846,Batman,1989,Joel Cutrara,actor,Crimelord #2,22.0
492376,Batman,1989,John Dair,actor,Ricorso,23.0
566810,Batman,1943,James Dime,actor,Henchman,NaN
583712,Batman,1943,Lester Dorr,actor,Agent on Plane [Ch. 10,NaN
587415,Batman,1989,Sam Douglas,actor,Lawyer,52.0
603215,Batman,1943,Kenne Duncan,actor,"Fred, the Mechanic [Ch. 5-6",NaN
608711,Batman,1989,Richard Durden,actor,TV Director,28.0
623596,Batman,1989,Keith Edwards,actor,Reporter,36.0
660655,Batman,1989,Christopher Fairbank,actor,Nic,24.0
695901,Batman,1943,Robert Fiske,actor,Foster [Ch. 1-4,NaN
702343,Batman,1943,Sam Flint,actor,Dr. G.H. Borden [Ch. 1,NaN
724284,Batman,1943,Jerry Frank,actor,Cave of Horrors Thug,NaN
...,...,...,...,...,...,...
2135388,Batman,1943,Harry Tenbrook,actor,Bartender,NaN
2211421,Batman,1943,Michael Vallon,actor,Preston [Ch. 10,NaN
2268244,Batman,1989,Lee Wallace,actor,The Mayor,11.0
2271582,Batman,1989,Tracey Walter,actor,Bob the Goon,10.0
2277651,Batman,1943,Anthony Warde,actor,Stone,NaN
2297719,Batman,1989,Anthony Wellington,actor,Patrolman at Party,39.0
2308509,Batman,1943,Dan White,actor,Mover with Pickup Truck,NaN
2311151,Batman,1943,Blackie Whiteford,actor,Barfly,NaN
2320017,Batman,1943,Billy Wilkerson,actor,Steve [Ch. 8,NaN
2322746,Batman,1989,Billy Dee Williams,actor,Harvey Dent,6.0
2332937,Batman,1943,Charles C. Wilson,actor,Police Captain Arnold,NaN
2334263,Batman,1943,Harry Wilson,actor,Henchman,NaN
2335194,Batman,1943,Lewis Wilson,actor,Batman,1.0
2335195,Batman,1943,Lewis Wilson,actor,Bruce Wayne,1.0
2344475,Batman,1989,Christian Wolf-La'Moy,actor,Taxi Driver,NaN
2344476,Batman,1989,Christian Wolf-La'Moy,actor,Joker's Car Owner,NaN
2348912,Batman,1989,Vincent Wong,actor,Crimelord #1,21.0
2359874,Batman,1989,Robert Wuhl,actor,Alexander Knox,4.0
2471856,Batman,1989,Kim Basinger,actress,Vicki Vale,3.0
2560390,Batman,1989,Lachele Carl,actress,TV Technician,30.0
2616205,Batman,1989,Priscilla Cory,actress,Beautiful Hostage,NaN
2665419,Batman,1989,Serena Destouche,actress,Extra,NaN
2821346,Batman,1989,Jerry Hall,actress,Alicia Hunt,9.0
2830831,Batman,1989,Kate Harper,actress,Anchorwoman,26.0
2861543,Batman,1989,Kit Hollerbach,actress,Becky,29.0
2862390,Batman,1989,Sharon Holm,actress,Mrs. Wayne,49.0
3202877,Batman,1943,Shirley Patterson,actress,Linda Page,4.0
3291717,Batman,1989,Pam Rose,actress,Party Guest at Wayne Manor,NaN
3293611,Batman,1989,Liza Ross,actress,Tourist Mom,45.0
3304401,Batman,1989,Rachel Ryan,actress,Corpse,NaN

In [26]:
a = see.year.nunique()
a

2

### How many roles were there in the movie "Inception"?

In [28]:
Inception = cast[cast.title == 'Inception']

In [32]:
len(Inception.type) #number of roles

77

In [33]:
Inception.type.nunique() #number of unique roles

2

### How many roles in the movie "Inception" are NOT ranked by an "n" value?

In [35]:
Inception.n.isnull().sum()

26

### But how many roles in the movie "Inception" did receive an "n" value?

In [36]:
Inception.n.notnull().sum()

51

### Display the cast of "North by Northwest" in their correct "n"-value order, ignoring roles that did not earn a numeric "n" value.

In [46]:
North = cast[cast.title == 'North by Northwest']
North_n = North[North.n.notnull()]
North_n.sort('n')

/Users/sheena/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:3: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  app.launch_new_instance()

,title,year,name,type,character,n
827711,North by Northwest,1959,Cary Grant,actor,Roger O. Thornhill,1.0
3308882,North by Northwest,1959,Eva Marie Saint,actress,Eve Kendall,2.0
1383389,North by Northwest,1959,James Mason,actor,Phillip Vandamm,3.0
2976957,North by Northwest,1959,Jessie Royce Landis,actress,Clara Thornhill,4.0
338312,North by Northwest,1959,Leo G. Carroll,actor,The Professor,5.0
2877697,North by Northwest,1959,Josephine Hutchinson,actress,Mrs. Townsend,6.0
1609857,North by Northwest,1959,Philip Ober,actor,Lester Townsend,7.0
1210346,North by Northwest,1959,Martin Landau,actor,Leonard,8.0
2322114,North by Northwest,1959,Adam Williams,actor,Valerian,9.0
1719980,North by Northwest,1959,Edward Platt,actor,Victor Larrabee,10.0
632374,North by Northwest,1959,Robert Ellenstein,actor,Licht,11.0
2178458,North by Northwest,1959,Les Tremayne,actor,Auctioneer,12.0
440966,North by Northwest,1959,Philip Coolidge,actor,Dr. Cross,13.0
1432366,North by Northwest,1959,Patrick McVey,actor,Sergeant Flamm,14.0
195115,North by Northwest,1959,Edward Binns,actor,Captain Junket,15.0
1314505,North by Northwest,1959,Ken Lynch,actor,Charley - Chicago Policeman,16.0

### Display the entire cast, in "n"-order, of the 1972 film "Sleuth".

In [51]:
Sleuth = cast[(cast.title == 'Sleuth') & (cast.year == 1972)]
a = Sleuth.sort('n')
a.name

/Users/sheena/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:2: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  from ipykernel import kernelapp as app

1619474      Laurence Olivier
309696          Michael Caine
354738         Alec Cawthorne
1391194    John (II) Matthews
2579049    Eve (III) Channing
1375438          Teddy Martin
Name: name, dtype: object

### Now display the entire cast, in "n"-order, of the 2007 version of "Sleuth".

In [52]:
Sleuth = cast[(cast.title == 'Sleuth') & (cast.year == 2007)]
a = Sleuth.sort('n')
a.name

/Users/sheena/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:2: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  from ipykernel import kernelapp as app

309697           Michael Caine
1227880               Jude Law
1714832          Harold Pinter
246165         Kenneth Branagh
354739     Alec (II) Cawthorne
2579048      Eve (II) Channing
3173313      Carmel O'Sullivan
Name: name, dtype: object

### How many roles were credited in the silent 1921 version of Hamlet?

In [56]:
Ham = cast[(cast.title == 'Hamlet') & (cast.year == 1921)]
Ham.type.count()

9

In [59]:
len(Ham.type) #should be same as count()

9

In [60]:
Ham.type.nunique()

2

### How many roles were credited in Branagh’s 1996 Hamlet?

In [61]:
Ham = cast[(cast.title == 'Hamlet') & (cast.year == 1996)]
Ham.type.count()

54

### How many "Hamlet" roles have been listed in all film credits through history?

In [62]:
Ham = cast[cast.title == 'Hamlet']
Ham.type.count()

313

### How many people have played an "Ophelia"?

In [65]:
Op = cast[cast.title == 'Ophelia']
Op

           title  year          name     type character   n
3272433  Ophelia  2018  Daisy Ridley  actress   Ophelia NaN
3499850  Ophelia  2018   Naomi Watts  actress  Gertrude NaN

In [64]:
Op.name.count()

2

### How many people have played a role called "The Dude"?

In [66]:
Dude = cast[cast.character == 'The Dude']

In [69]:
Dude.name.nunique()

17

### How many people have played a role called "The Stranger"?

In [70]:
Strange = cast[cast.character == 'The Stranger']

In [71]:
Strange.name.nunique()

197

In [72]:
Strange.name.count()

208

### How many roles has Sidney Poitier played throughout his career?

In [75]:
Sid = cast[cast.name == 'Sidney Poitier']
Sid

,title,year,name,type,character,n
1724587,A Patch of Blue,1965,Sidney Poitier,actor,Gordon Ralfe,1.0
1724588,A Piece of the Action,1977,Sidney Poitier,actor,Manny Durrell,1.0
1724589,A Raisin in the Sun,1961,Sidney Poitier,actor,Walter Lee Younger,1.0
1724590,A Warm December,1973,Sidney Poitier,actor,Dr. Matt Younger,1.0
1724591,All the Young Men,1960,Sidney Poitier,actor,Sgt. Eddie Towler,2.0
1724592,Band of Angels,1957,Sidney Poitier,actor,Rau-Ru,3.0
1724593,Blackboard Jungle,1955,Sidney Poitier,actor,Gregory W. Miller,10.0
1724594,Brother John,1971,Sidney Poitier,actor,John Kane,1.0
1724595,Buck and the Preacher,1972,Sidney Poitier,actor,Buck,1.0
1724596,"Cry, the Beloved Country",1951,Sidney Poitier,actor,Reverend Msimangu,3.0
1724597,Duel at Diablo,1966,Sidney Poitier,actor,Toller,2.0
1724598,Edge of the City,1957,Sidney Poitier,actor,Tommy Tyler,2.0
1724599,For Love of Ivy,1968,Sidney Poitier,actor,Jack Parks,1.0
1724600,Go Man Go,1954,Sidney Poitier,actor,Inman Jackson,3.0
1724601,"Good-bye, My Lady",1956,Sidney Poitier,actor,Gates Watson,4.0
1724602,Guess Who's Coming to Dinner,1967,Sidney Poitier,actor,John Prentice,2.0
1724603,In the Heat of the Night,1967,Sidney Poitier,actor,Virgil Tibbs,1.0
1724604,Let's Do It Again,1975,Sidney Poitier,actor,Clyde Williams,1.0
1724605,Lilies of the Field,1963,Sidney Poitier,actor,Homer Smith,1.0
1724606,Little Nikita,1988,Sidney Poitier,actor,Roy Parmenter,1.0
1724607,No Way Out,1950,Sidney Poitier,actor,Dr. Luther Brooks,4.0
1724608,Paris Blues,1961,Sidney Poitier,actor,Eddie Cook,3.0
1724609,Porgy and Bess,1959,Sidney Poitier,actor,Porgy,1.0
1724610,Pressure Point,1962,Sidney Poitier,actor,Doctor,1.0
1724611,Red Ball Express,1952,Sidney Poitier,actor,Robertson,5.0
1724612,Sepia Cinderella,1947,Sidney Poitier,actor,Night Club Extra,NaN
1724613,Shoot to Kill,1988,Sidney Poitier,actor,Warren Stantin,1.0
1724614,Sneakers,1992,Sidney Poitier,actor,Donald Crease,4.0
1724615,Something of Value,1957,Sidney Poitier,actor,Kimani Wa Karanja,13.0
1724616,The Bedford Incident,1965,Sidney Poitier,actor,Ben Munceford,2.0
1724617,The Defiant Ones,1958,Sidney Poitier,actor,Noah Cullen,2.0
1724618,The Greatest Story Ever Told,1965,Sidney Poitier,actor,Simon of Cyrene,21.0
1724619,The Jackal,1997,Sidney Poitier,actor,FBI Deputy Director Carter Preston,3.0
1724620,The Long Ships,1964,Sidney Poitier,actor,Aly Mansuh,2.0
1724621,The Lost Man,1969,Sidney Poitier,actor,Jason Higgs,1.0
1724622,The Mark of the Hawk,1957,Sidney Poitier,actor,Obam,2.0
1724623,The Organization,1971,Sidney Poitier,actor,Virgil Tibbs,1.0
1724624,The Slender Thread,1965,Sidney Poitier,actor,Alan Newell,1.0
1724625,The Wilby Conspiracy,1975,Sidney Poitier,actor,Shack Twala,1.0
1724626,They Call Me Mister Tibbs!,1970,Sidney Poitier,actor,Virgil Tibbs,1.0
1724627,"To Sir, with Love",1967,Sidney Poitier,actor,Mark Thackeray,1.0
1724628,Uptown Saturday Night,1974,Sidney Poitier,actor,Steve Jackson,1.0
1724629,Virgin Island,1958,Sidney Poitier,actor,Marcus,3.0

In [76]:
Sid.title.count()

43

In [78]:
Sid.type.nunique()

1

### How many roles has Judi Dench played?

In [81]:
Judy = cast[cast.name == 'Judi Dench']

In [82]:
Judy.title.count()

54

### List the supporting roles (having n=2) played by Cary Grant in the 1940s, in order by year.

In [90]:
c = cast[(cast.name == 'Cary Grant') & (cast.n == 2) & (cast.year >= 1940) & (cast.year <= 1949)]
c.sort('year')

/Users/sheena/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:2: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  from ipykernel import kernelapp as app

                   title  year        name   type    character    n
827708  My Favorite Wife  1940  Cary Grant  actor         Nick  2.0
827718    Penny Serenade  1941  Cary Grant  actor  Roger Adams  2.0

### List the leading roles that Cary Grant played in the 1940s in order by year.

### How many roles were available for actors in the 1950s?

In [95]:
h = cast[(cast.year >= 1950) & (cast.year >= 1959) & (cast.type == 'actor')]
h.count()

title        1878122
year         1878122
name         1878122
type         1878122
character    1878122
n            1192123
dtype: int64

### How many roles were avilable for actresses in the 1950s?

In [96]:
h = cast[(cast.year >= 1950) & (cast.year >= 1959) & (cast.type == 'actress')]
h.count()

title        962616
year         962616
name         962616
type         962616
character    962616
n            611664
dtype: int64

### How many leading roles (n=1) were available from the beginning of film history through 1980?

In [100]:
z = cast[(cast.year <= 1980) & (cast.n == 2)]
z.count()

title        59830
year         59830
name         59830
type         59830
character    59830
n            59830
dtype: int64

### How many non-leading roles were available through from the beginning of film history through 1980?

In [102]:
z1 = cast[(cast.year <= 1980) & (cast.n != 2)]
z1.count()

title        1090685
year         1090685
name         1090685
type         1090685
character    1090685
n             656212
dtype: int64

### How many roles through 1980 were minor enough that they did not warrant a numeric "n" rank?

In [116]:
z2 = cast[cast.year <= 1980]
z2['n'].notnull().sum()

716042